### ISSUE TITLE
Does not apply immediately after a logout

### ISSUE THREAD

**Issue by kav2k** [kav2k/fl_favourites#1]
User reported that logging out and back in does not activate the extension immediately.

Needs investigation.

**Comment by kav2k** [comment]
So far, cannot reproduce.

**Comment by afallingkitten** [comment]
The url for when I initially log in is the same as the url after I reload the page. [http://fallenlondon.storynexus.com/Gap/Load?content=%2fStorylet%2fAvailable]

The same happens if I log in, go to a different tab (i.e. the Myself tab), then back to the story tab. I thought that might have an effect, because changing tabs adds a # to the end of the url, but I still have to refresh the page.

Also whether or not I have an option marked seems to have no effect on this.

AH HA! I found the issue. I disabled all my extensions, and was re-enabling them one at a time, to see if any were the culprit. And as it turns out, it's Tampermonkey doing it. If I disable Tampermonkey, I don't have to refresh the page.

**Comment by kav2k** [comment]
I also use Tampermonkey, for the 5-card lodgings resized script, and I don't have that effect. So it's some specific userscript you have that's interfering.

**Comment by kav2k** [comment]
Closing this as it only happens as a result of interference, but I would like to know still what's interfering.

**Comment by kav2k** [comment]
Tracked this very improbable bug down. Curious issue with Chrome itself. I'll keep this closed as a duplicate of #7, but fix is forthcoming.
